name: Tests
on:
  push:
    branches: [main]
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  first-job:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name:
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "$MY_SECRET" | wc
