name: Tests
on:
  push:
    branches: [main]
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  install-dependencies-and-caching:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Step 2 - GitHub Action if statement (true)
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "$MY_SECRET" | wc
